### ISSUE TITLE
@shopify/app-bridge-utils package is no longer supported

### ISSUE THREAD

**Issue by VladimirZubenko** [Shopify/shopify-frontend-template-react#198]
# Issue summary

@shopify/app-bridge-utils package is no longer supported and should be changed.

## Steps to reproduce the problem

1. Change the import:
import { authenticatedFetch } from "@shopify/app-bridge-utils";
to:
import { authenticatedFetch } from "@shopify/app-bridge/utilities";

https://github.com/Shopify/shopify-frontend-template-react/blob/16bf98eff0fe8eeb7f4b37a063188d0faab1f67e/hooks/useAuthenticatedFetch.js#L1

2. Remove unnecessary package:
https://github.com/Shopify/shopify-frontend-template-react/blob/main/package.json#L21

**Comment by pnmcosta** [comment]
I was getting [invalid hook call warning](https://react.dev/warnings/invalid-hook-call-warning), changing this and removing the package fixed it for me.

**Comment by gching** [comment]
This can be closed given #183 :+1:
