### ISSUE TITLE
App Bridge v4 migration guide auth flow broken

### ISSUE THREAD

**Issue by Arkansio** [Shopify/shopify-frontend-template-react#275]
# Issue summary

I migrated from App Bridge v3 to App Bridge v4, problem is, authentification doesn't work anymore, I'm using it in complementary the template with shopify app express. When the session exist in the database no problem, but when session has to be created there the problem. Also I noticed there's no call at the ExitIframe at all. I don't know what's not working. I just know that session is invalid.

## Expected behavior

It should create a session and just work.

## Actual behavior

I got redirected on a NotFound page

## Steps to reproduce the problem

1. Migrate to App Bridge v4

## Specifications

- Browser: Chrome
- Device: MacBook Pro
- Operating System: MacOS

Thanks for your help. I'm going crazy on this problem.

**Comment by Arkansio** [comment]
My bad, it was due to the vite plugin :

`import { createHtmlPlugin } from 'vite-plugin-html';`

It took me days to realise. I added it following the need to change the variable in the index.html in a clean way. I never suspected it was that, because even when removing the variable and keeping the plugin it still didn't work. But it seems that just the plugin itself mess everything up. Well, I guess I should train my debug skills, because I literally took 4 days to understand it. Sorry.

**Comment by wntechs** [comment]
@Arkansio you are right, I did the same to replace the shopify_api_key dynamically in index.html and encountered the similar problem. I am not sure what's wrong with vite-plugin-html but we definitely need a clean way to make this dynamically. Currently I had to hardcode the api_key in html file. Did you find any viable solution for this yet?
